baseurl = "http://t32k.me/mol/"
languageCode = "en-us"
title = "MOL"
publishdir = "mol"
contentdir = "_content"
layoutdir = "_layouts"
staticdir = "_static"

[params]
  description = "Tesla's Awesome Hugo Site"
  author = "Koji Ishimoto"